### ISSUE TITLE
Adding an index through ghost_adapter breaks

### ISSUE THREAD

**Issue by grdw** [WeTransfer/ghost_adapter#59]
**Describe the bug**
When creating a new table through ghost_adapter and adding the sufficient indexes, ghost adapter crashes.

Example migration:
```ruby
class CreateThings < ActiveRecord::Migration[6.1]
  def change
    create_table :things, id: :bigint do |t|
      t.string :public_id
      t.datetime :created_at
      t.datetime :updated_at
    end

    add_index :things, :public_id
  end
end
```

It will break on the `add_index` method. 

```
Caused by:
ArgumentError: wrong number of arguments (given 3, expected 2)
```

When running the migration with `GHOST_MIGRATE=0 bundle exec rake db:migrate` all seems to work fine.

**To Reproduce**
1. Create a migration with/without a new table, but adding an index to a table
2. Run the migration like `GHOST_MIGRATE=1 bundle exec rake db:migrate`
3. See error

**Expected behavior**
To not see the error 😬 

**Screenshots**
\-

**Desktop (please complete the following information):**
 - OS: Ubuntu x86_64 x86_64 x86_64 GNU/Linux
 
**Smartphone (please complete the following information):**
\-

**Additional context**
\-

**Comment by acroos** [comment]
@grdw is there more stacktrace you can add?

**Comment by acroos** [comment]
I found the issue.  In Rails 6.1, the `add_index` and `remove_index` method signatures changed (as well as the `add_index_options` and `index_name_for_remove` signatures)
