### ISSUE TITLE
Double ALTER TABLE statements.

### ISSUE THREAD

**Issue by grdw** [WeTransfer/ghost_adapter#64]
**Is your feature request related to a problem? Please describe.**
Currently we're doing a migration which goes like this:

```ruby
add_reference :table, :resource, polymorphic: true
```

This in turn causes **two copy cycles** in ghost, I'm assuming one for the new columns `resource_type` and `resource_id` and another one for the indexes `(resource_type, resource_id)`. This is more of an open question: is it possible to do this in a single `ALTER TABLE` statement or is that simply impossible? 🤔

**Comment by acroos** [comment]
Thanks for pointing this out! We _could_ consider overriding this method to make it a single alter table statement? One solution would be to do a `change_table` with `bulk: true` which will batch all changes up into a single alter table.

**Comment by acroos** [comment]
> Thanks for pointing this out! We _could_ consider overriding this method to make it a single alter table statement?

Overriding the method comes with more future maintenance and potential for bugs, though, so I'm hesitant to do this

**Comment by grdw** [comment]
> One solution would be to do a change_table with bulk: true which will batch all changes up into a single alter table.

This is what I'm planning to do, so rewrite it to:

```ruby
change_table :things, bulk: true do |t|
  t.string :resource_type
  t.bigint :resource_id
  t.index [:resource_type, :resource_id], name: 'index_things_on_resource'
end
```

**Comment by acroos** [comment]
@grdw looking at the ActiveRecord code for this [starting here](https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L873-L875) and [continuing here](https://github.com/rails/rails/blob/35555486d3decd086ea2cb8d7a0bd36a8c0c5503/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L140-L152) we can see the intention is to have multiple alter table statements.  I've tested this out with trying to add `bulk: true` to the `add_reference`, but this is not an option that gets used.  I don't think we should change this behavior as we would need to override more default ActiveRecord behavior when there exists a workaround for this that solves the problem
